printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: false
trailingComma: none
bracketSpacing: true
arrowParens: always
bracketSameLine: true
plugins:
  - prettier-plugin-astro
  - prettier-plugin-svelte
overrides:
  - files: "*.astro"
    options:
      parser: "astro"
  - files: "*.svelte"
    options:
      parser: "svelte"

# astro
astroAllowShorthand: true
astroSkipFrontmatter: false
